### ISSUE TITLE
Expand and better document imputation_strategy in TargetEncoder

### ISSUE THREAD

**Issue by sborms** [PythonPredictions/cobra#117]
Check if the imputation_strategy parameter in TargetEncoder can also take median (+ document better: mean, median, min, max), and see if PIGs also compute the desired imputation option

**Comment by patrickleonardy** [comment]
I added the median imputation functionally and adapted the explanation in the PreProcessor.from_params() function.
Is there a better place to give this explanation ?

I am also wondering: How should we include the not seen categories in the PIGs ? For the moment the not seen categories are put into the others bin in the pig_tables.

Is there also a place where I could give an explanation with some tables? I think this could clarify what is happening quite easily. (I do not think that the blog post is the right place for that)

**Comment by sandervh14** [comment]
Hi Patrick! Nice initiative!

Don't be afraid to always already commit *and push*: you are working on an issue branch, none of your changes while still working on it will go to the development branch as long as nobody merges with a pull request. If you feel like your changes were very experimental though so far, you can stash them instead of merging.

For the explanations: I like very much that you already wrote them in the docstring. I'd put only a high-level description in the docstring of the preprocessor though, and you can refer to the docs of the TargetEncoder for full details, to avoid having to write (and maintain) the target encoder's documentation in two spots.

As for the others bin: since not a lot of observations (samples) are in the merged categories ("not seen" categories), I've never bothered about this, and so far I thought it is therefore not a problem that they appear on PIGs just bundled in one category "others". Nevertheless, if you would like to visualize on the PIGs the amounts of the _original_ categories rather than the merged "other" category, then feel free to adapt that (or support both and enable your new visualization with a switch).

For long explanations, including example tables, I see two options:
1. You can try to include them in the docstring in a way that the documentation creator can render it nicely, for example with https://tabletomarkdown.com/ or https://stackoverflow.com/questions/48233783/syntax-to-put-images-in-rst (to be checked what works)
2. You can put this long explanation with tables also as a notebook in the tutorials folder, and point to that place.
3. (The blog post still is an option too, just with the downside that then this explanation does not live in the Cobra Github repo, but if you clearly link to it, just like in solution 2., also fine.)

**Comment by patrickleonardy** [comment]
I let the PIGs be as they are as I do not think splitting the "other" category up has a lot of value. 

But I am wondering is there some better explanation of the target encoding ? I implemented the median imputation as it was done with `min` and `max` by taking the median over all encoded observations (excluding the once that we can not know). 
In the mean implementation however the global mean is taken, this seems logic to me but I am wondering if this is the good approach. Is the implementation of median correct like this ? Or should I rather only implement it for the numerical target variables and then take the mean over the hole target_variable (this would be closer to the mean implementation).
