### ISSUE TITLE
Fixing FutureWarnings

### ISSUE THREAD

**Issue by patrickleonardy** [PythonPredictions/cobra#156]
# Fixing FutureWarnings

Task: 
Currently there are a lot of FutureWarinings (generated by pandas) popping up in Cobra that clutter up once notebook. We should change this behavior such that cobra is up to date.
 

## Task Description

This issue will:
- Adapt the cobra code such that no more FutureWarnings appear. 
- Cobra get a setting that allows the user to suppress FutureWarings 
- We could also see if it is possible to implement some checks that we are up to date if something changes in the libraries that we are using.

**Comment by ZlaTanskY** [comment]
Depending on what the warnings are, I disagree with adding a cobra setting to suppress the warnings. If the warnings are on our (cobra) side, we should fix them instead of suppressing them.

**Comment by sandervh14** [comment]
I see in the pull request that you fixed the .loc stuff to avoid the FutureWarnings. With the above two comments, don't ditch the pull request you've made however, it's still relevant to #160! Maybe link the pull request to #160 instead of this issue #156, and if this issue #156 is *only* about suppressing future warnings, then you can close this one since both me and Jano voted against supressing.

**Comment by patrickleonardy** [comment]
I did nothing to suppress them I only changed the code that was raising FutureWarnings to an other syntax that does not raise a FutureWarning. Including things that are linked to #160 
When you say that I should not ditch it you mean that I should not yet merge it and only merge it with #160 ?
