### ISSUE TITLE
Preprocessing should have option verbose

### ISSUE THREAD

**Issue by JanBenisek** [PythonPredictions/cobra#41]
In cases when preprocessing takes longer, it'd be useful to see what is happening inside.
We can implement `verbose` boolean parameter which when set to True with print what is happening ("processing variable X ...")

Optionally, the `verbose` can be setup in the same was as in sklearn - it accepts integer and the bigger the integer, the more details are printed.

**Comment by sandervh14** [comment]
Hi Honza & Sam, I wrote down an idea of adding progress bars with `tqdm` (https://github.com/tqdm/tqdm). 
For forward feature selection, in my case.
But I think for both preprocessing & feature selection, to assess how *long* something will still run, a progress bar is more user friendly than just printing verbose statements.

**Comment by sborms** [comment]
I also checked this issue and there are already some logs assembled, mainly in `PreProcessor.fit()`.  These logs are just dumped to an external file, right? If not, and they are also printed to the console, this issue never was one and is fixed, albeit in a rudimentary way.

Otherwise, and maybe tout court, progress bars make most sense indeed. If you are familiar with how `tqdm` works Sander, can you also integrate it to `PreProcessor.fit()` and `PreProcessor.transform()`?
