### ISSUE TITLE
Preprocessing - target_encoder

### ISSUE THREAD

**Issue by JanBenisek** [PythonPredictions/cobra#67]
- [x] Discuss the methodology - how to do incidence replacement for continuous target? Currently we calculate average per group and size of the group and do the replacement. This will be working for continuous target as well.
- [x]  Document and write/modify unit tests
- [ ] If time permits, this is a good opportunity to implement more sophisticated encoding - see #24 and #61

**Comment by sandervh14** [comment]
I've reviewed the TargetEncoder class for its applicability in linear regression. It will work for linear regression out of the box, but I want to list a few attention points.

First of all, next I'll add unit tests for the regression case.

Things that I think are attention points with the TargetEncoder:
- We mention that the mean encoding scheme of the target encoder may be prone to overfitting, but that this is tackled here with additive smoothing, *however, the default weight of additive smoothing is 0*, meaning additive smoothing is disabled by default and we don't warn the user that this may lead to overfitting.
  - I would like to at least warn the user when the additive smoothing weight is 0.
  - maybe even better would be to warn the user that the additive smoothing weight is 0, when there are values in the categorical variable for which there are not a lot of observations (value count), increasing the risk of overfitting with the mean encoding scheme of the target encoder.
- I added the formulas applied in the TargetEncoder class's docstring:

```
- with a binary classification target, a value of a categorical variable is
    replaced with:

    [count(variable=value) * P(target=1|variable=value) + weight * P(target=1)]
    / [count(variable=value) + weight]

    - with a regression target, a value of a categorical variable is replaced
    with:

    [count(variable=value) * E(target|variable=value) + weight * E(target)]
    / [count(variable=value) + weight]
```
So setting the weight for additive smoothing could in theory be done strategically: e.g. setting the weight to the count of the value that is least occurring in the categorical variable, to counteract possible overfitting if this value count is really low.
However, in practice, this is not handy in Cobra because we use the target encoder with one additive smoothing weight shared *for all categorical columns* to transform. So:
  - one solution for that could be to change the smoothing weight into a dictionary of weights per categorical column
  - another solution could be to change the _value count_ in the beginning of the target encoding formula (see above) into the _value occurrence percentage_ (i.e. P(variable=value) instead of count(variable=value)). Then you could impose a smoothing weight equal to a minimum _value occurrence percentage_, which is better applicable across multiple columns.

And one side question: when would someone use the min or max imputation strategies instead of the mean imputation strategy?

**Comment by sborms** [comment]
As discussed with Sander:

- Good idea to add a warning in the documentation regarding the by default overfitting weight setting.
- Very handy docstring addition!
- Preference to go for the second proposed solution. Best to set up a separate issue for this, and work it out later. The weight parameter would then become a minimum_weight parameter (can keep same parameter name, just change documentation), between 0 and 1.
- I don't see that many cases for min/max encoding either, but let's keep it as optionality. Could be if one deliberately wants under/overestimation for some reason.

**Comment by sandervh14** [comment]
Wrapping this up:
- the current target encoding approach works for linear regression, as verified in the extra unit tests.
- documentation of the target encoder was modified to reflect the dual applicability (binary classification and linear regression).
- for now, a warning tells the user that the default additive smoothing weight makes the target encoder a bit more prone to overfitting; issue #83 was created to bundle the suggestions we made above to handle it better in the near future. Right now we need an MVP for linear regression, we must fix some other issues first.
